# WEB 계정 배포
---
- name: add WAS Admin user
  hosts: "{{ target }}"
  become: yes
  gather_facts: yes

  tasks:
  - name: del user
    ansible.builtin.user:
      name: webadm
      state: absent
      remove: yes
      force: yse

  - name: Add secu group
    group:
      name: admin
      state: present
      gid: 2000
  
  - name: Add user webadm
    user:
      name: webadmin
      shell: /bin/bash
      state: present
      create_home: true
      home: /product/apache2459/
      uid: 2001
      group: work
  
  - name: Create a password for user
    user:
      name: webadmin
      password: "{{ '1234qwer' | password_hash('sha512') }}"