# # sycros(서버모니터링) 계정 배포
---
- name: add sycros user
  hosts: "{{ target }}"
  become: yes
  gather_facts: yes

  tasks:
  - name: Add mo group
    group:
      name: mo
      state: present
      gid: 6000
  
  - name: Add user webadm
    user:
      name: sycros
      shell: /bin/bash
      state: present
      create_home: true
      home: /home/sycros/
      uid: 6002
      group: mo
  
  - name: Create a password for user
    user:
      name: sycros
      password: "{{ '1234qwer' | password_hash('sha512') }}"
