#linux 계정 passwod변경 
---
- name: Change sysadm passwd
  hosts: "{{ target }}"
  #hosts: localhost
  become: yes
  gather_facts: no

  vars:
    myuser: "swansible"
    mypassword: "1234qwer"

  tasks:
  - name: Change sysadm passwd 
    ansible.builtin.user:
      name: "{{ myuser }}"
      password: "{{ mypassword | password_hash('sha512')}}"
    register: shell_result