# 프로메테우스 node exporter agent 배포 
---
- name: Install_Node_Exporter
  hosts: "{{ target }}"
  become: yes
  gather_facts: no
  become_user: root

  var:
    - node_exporter_dir: /home/sysadm/node_exporter-1.7.0.linux-amd64
    - node_exporter_user: swnodeexp

  tasks:
    - name: copy file to remote
      copy:
        src: /APP/ansible/playbooks/upload_files/node_exporter-1.7.0.linux-amd64.tar.gz
        dest: /home/sysadm/node_exporter-1.7.0.linux-amd64.tar.gz
        force: no
      register: result

    - name: Extract a file
      unarchive:
        src: /home/sysadm/node_exporter-1.7.0.linux-amd64.tar.gz
        dest: /home/sysadm
        remote_src: yes
      when: result is changed

    - name: check if node export exist
      stat:
        path: "{{ node_exporter_dir}}"
      register: __check_node_exporter_present

    - name: move the binary to the final destination
      copy:
        src: "{{ node_exporter_dir }}/node_exporter"
        dest: "/usr/local/bin"
        mode: 0755
        remote_src: yes
      when: __check_node_exporter_present.stat.exists

    - name: clean temp dir
      file:
        path: "{{ node_exporter_dir }}"
        state: absent

    - name: create node exporter user 
      user:
        name: "{{ node_exporter_user }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        create_home: false
      when: __check_node_exporter_present.stat.exists

    - name: Install Service
      template:
        src: deploy_node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: 0755
      register: install

    - name: reload_daemon_and_restart_node_exporter
      systemd:
        name: node_exporter
        state: restarted
        daemon_reload: yes
        enabled: yes
      when: install is changed

    - name: service always started
      systemd:
        name: node_exporter
        state: started
        enabled: yes

