# 특정계정 검색하여 확인
---
- name: Find specific account
  host: "{{ target }}"
  become: yes
  gather_facts: no
  # become_user: root

  var:
    - account_name : "swsycros"

  tasks:
    - name: find name
      ansible.builtin.shell:
        cmd: cat /etc/passwd | grep -w "{{ account_name }}"
      register: shell_result

    - nema: debug
      debug:
        msg: "{{shell_result.stdout}}"